packages:
  - software/umap
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  # SDK packages - EXACT VERSIONS (no ^ or ~)
  '@milaboratories/ts-builder': 1.2.2
  '@milaboratories/ts-configs': 1.2.0
  '@platforma-sdk/workflow-tengo': 5.8.0
  '@platforma-sdk/model': 1.51.9
  '@platforma-sdk/ui-vue': 1.51.9
  '@platforma-sdk/tengo-builder': 2.4.8
  '@platforma-sdk/package-builder': 3.11.0
  '@platforma-sdk/block-tools': 2.6.29
  '@platforma-sdk/eslint-config': 1.2.0
  '@platforma-sdk/test': 1.51.9
  '@milaboratories/helpers': 1.13.0
  '@milaboratories/graph-maker': 1.1.213
  '@milaboratories/multi-sequence-alignment': 1.45.11

  '@milaboratories/software-pframes-conv': 2.2.9
  '@platforma-open/milaboratories.runenv-python-3': 1.6.2

  # Common dependencies - can use ^ or ~
  '@vueuse/core': ^13.3.0
  '@types/node': ^24.5.2
  'vue': ^3.5.24
  'typescript': ~5.6.3
  'turbo': ^2.6.3
  'vite': ^6.2.2
  'vitest': ^4.0.7
  'eslint': ^9.25.1
  '@changesets/cli': ^2.29.8
  'js-yaml': ^4.1.0
  'shx': ^0.4.0
