packages:
  - software/umap
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/model': ^1.43.2
  '@platforma-sdk/ui-vue': ^1.43.2
  '@platforma-sdk/workflow-tengo': ^5.3.0
  '@platforma-sdk/block-tools': ^2.6.7
  '@platforma-sdk/test': ^1.43.10
  '@platforma-sdk/tengo-builder': ^2.2.0
  '@platforma-sdk/package-builder': ^3.8.1
  '@platforma-sdk/eslint-config': ^1.1.0
  '@milaboratories/graph-maker': ^1.1.166
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  '@milaboratories/software-pframes-conv': ^2.2.7
  '@platforma-open/milaboratories.runenv-python-3': ^1.4.12

  '@vueuse/core': ^13.3.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'typescript': ~5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.5.4

  'vite': ^6.2.2
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.4

  'js-yaml': ^4.1.0

  '@changesets/cli': ^2.29.4
